#!/bin/bash
 
# AUTHOR:   (c) Rob W 2012
#           modified by MHC (http://askubuntu.com/users/81372/mhc)
#           and by Rodolfo Carvalho
#			and by Alex Farias (https://github.com/astfarias/)
# NAME:     GIFRecord 0.1-mint
# DESCRIPTION:  A script to record GIF screencasts.
# LICENSE:  GNU GPL v3 (http://www.gnu.org/licenses/gpl.html)
# DEPENDENCIES:   byzanz,zenity,notify-send,xrectsel

set -e

# Time and date
TIME=$(date +"%Y-%m-%d_%H%M%S")
 
# Delay before starting
DELAY=2
 
# Standard screencast folder
FOLDER="$HOME//Vídeos/Gravações/videos"
 
# Default recording duration
DEFDUR=10
 
# Sound notification to let one know when recording is about to start (and ends)
beep() {
    paplay /usr/share/sounds/freedesktop/stereo/message-new-instant.oga &
}
 
# Custom recording duration as set by user
USERDUR=$(zenity --entry --title "Recoding duration" --text "Please enter the screencast duration in seconds:" --width 200 --height 100 2>/dev/null)
 
# Duration and output file
if [ $USERDUR -gt 0 ]; then
    D=$USERDUR
else
    D=$DEFDUR
fi
 
# xrectsel from https://github.com/lolilolicon/xrectsel
XRECTSEL=$( xrectsel "x:%x y:%y w:%w h:%h "|sed 's/ /\n/g'  ) || exit -1

read X < <(awk -F: '/x:/{ print $2 }' <<< "$XRECTSEL")
read Y < <(awk -F: '/y:/{ print $2 }' <<< "$XRECTSEL")
read W < <(awk -F: '/w:/{ print $2 }' <<< "$XRECTSEL")
read H < <(awk -F: '/h:/{ print $2 }' <<< "$XRECTSEL")

 
# Notify the user of recording time and delay
notify-send "GIFRecorder" "Recording duration set to $D seconds. Recording will start in $DELAY seconds."
 
#Actual recording
sleep $DELAY
beep
byzanz-record -c --verbose --delay=0 --duration=$D --x=$X --y=$Y --width=$W --height=$H "$FOLDER/GIFrecord_$TIME.gif"
beep
 
# Notify the user of end of recording.
notify-send "GIFRecorder" "Screencast saved to $FOLDER/GIFrecord_$TIME.gif"
